# Generated by Django 4.0.4 on 2022-05-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='id',
        ),
        migrations.AlterField(
            model_name='study',
            name='category',
            field=models.CharField(choices=[('관찰연구', '관찰연구'), ('중재연구', '중재연구'), ('기타', '기타')], max_length=20, verbose_name='연구종류'),
        ),
        migrations.AlterField(
            model_name='study',
            name='number',
            field=models.CharField(max_length=31, primary_key=True, serialize=False, verbose_name='과제번호'),
        ),
        migrations.AlterField(
            model_name='study',
            name='scope',
            field=models.CharField(choices=[('국내다기관', '국내다기관'), ('단일기관', '단일기관')], max_length=20, verbose_name='연구범위'),
        ),
    ]
